// Generated by cbindgen — do not edit by hand.

#ifndef SHADOWVPN_CORE_H
#define SHADOWVPN_CORE_H

#pragma once

/* Regenerate with `cbindgen --config cbindgen.toml --output include/shadowvpn_core.h` */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Destination Connection ID length, in bytes. Fixed and shared by both ends.
 * 8 is the most common QUIC DCID length, so it is unremarkable to a classifier.
 */
#define DEFAULT_DCID_LEN 8

/**
 * Upper bound on the obfs header size (`1 + max DCID + max PN`), used to size
 * receive buffers with headroom regardless of the negotiated `dcid_len`.
 */
#define MAX_HEADER ((1 + 20) + 4)

/**
 * Control-protocol version. Bumped only on an incompatible frame change.
 */
#define VERSION 1

/**
 * No free address remained in the server's pool.
 */
#define POOL_EXHAUSTED 1

/**
 * The server is not configured to assign addresses.
 */
#define NOT_ENABLED 2

/**
 * AEAD nonce length in bytes. All supported ciphers use a 12-byte nonce.
 */
#define NONCE_LEN 12

/**
 * AEAD authentication tag length in bytes. All supported ciphers use a
 * 16-byte (128-bit) Poly1305 / GCM tag.
 */
#define TAG_LEN 16

/**
 * Default tunnel MTU for the TUN interface, in bytes.
 *
 * 1400 leaves comfortable headroom under a typical 1500-byte path MTU for the
 * outer IP + UDP headers and the ShadowVPN crypto overhead (salt + tag), so
 * that an encrypted datagram is unlikely to fragment on a normal Ethernet
 * path.
 */
#define DEFAULT_TUN_MTU 1400

/**
 * A generous upper bound on the plaintext IP packet size we will read from the
 * TUN device in a single read, in bytes.
 *
 * This is the largest IPv4/IPv6 datagram (65535) and bounds the plaintext
 * buffer size regardless of the configured MTU.
 */
#define MAX_IP_PACKET 65535

/**
 * C-compatible egress callback. Invoked from the data-plane tokio runtime
 * whenever a decrypted IP packet (or a synthesized chinadns response) is bound
 * for Swift's `NEPacketTunnelFlow`. Swift guarantees `ctx` stays live between
 * `svpn_tun_start` and the join performed by `svpn_tun_stop_blocking`.
 */
typedef void (*SvpnWritePacket)(void *ctx, const uint8_t *data, uintptr_t len);

/**
 * Initialize logging (os_log bridge + panic hook). Safe to call more than once.
 */
void svpn_core_init(void);

/**
 * Emit a log line from the NetworkExtension host (ObjC) into the same os_log
 * pipeline the data plane uses, so NE lifecycle events — start/stop,
 * sleep/wake, errors — interleave with engine output on one timeline.
 *
 * `level`: 0 = error, 1 = warn, 2 = info, 3 = debug, 4 = trace; anything else
 * is treated as info. No-op on a NULL or non-UTF-8 `msg`.
 *
 * # Safety
 * `msg` must point to a NUL-terminated UTF-8 string or be NULL.
 */
void svpn_core_log(int level, const char *msg);

/**
 * Set the App Group container path where the FFI may stage logs / cache.
 * `dir` may be NULL or empty. Currently advisory: ShadowVPN's data plane keeps
 * no on-disk state of its own (chnroute is passed by absolute path in
 * `config_json`), but the hook mirrors meow's `*_set_home_dir` so the Swift
 * side has a stable place to point future file-backed logging at.
 *
 * # Safety
 * `dir` must point to a NUL-terminated UTF-8 string or be NULL.
 */
void svpn_core_set_home_dir(const char *dir);

/**
 * Return the last error message for the calling thread. The pointer is owned
 * by the crate and valid until the next error is set on the same thread — copy
 * immediately if retention is needed.
 */
const char *svpn_core_last_error(void);

/**
 * Resolve the bypass-CIDR file for an ISO country code, extracting it from the
 * bundled MaxMind GeoLite2 Country mmdb the first time and caching it.
 *
 * Writes the absolute path of the cache file (`<cache_dir>/chnroute-<COUNTRY>-
 * <mmdb_len>.txt`, plain `a.b.c.d/len`-per-line text) into `out`/`out_cap`,
 * NUL-terminated. Returns the number of bytes the path needs (excluding the
 * NUL); if the return value is `>= out_cap` the path was truncated — allocate
 * `ret + 1` and call again. Returns `-1` on error (inspect
 * `svpn_core_last_error`): a missing/invalid mmdb, an unknown country, or an
 * unwritable cache directory.
 *
 * The expensive mmdb walk runs at most once per `(country, mmdb)`; later calls
 * return the cached path immediately. Swift parses the returned file for
 * `NEPacketTunnelNetworkSettings.excludedRoutes` and passes the same path back
 * as `config_json["chnroute_path"]` for the chinadns decision.
 *
 * # Safety
 * `mmdb_path`, `country`, and `cache_dir` must each be NUL-terminated UTF-8 C
 * strings. `out` must reference `out_cap` writable bytes if non-NULL.
 */
int svpn_country_cidrs_file(const char *mmdb_path,
                            const char *country,
                            const char *cache_dir,
                            char *out,
                            int out_cap);

/**
 * Start the ShadowVPN data plane with a Swift-owned egress callback and a JSON
 * config (see [`config::RuntimeConfig`] for the schema). The ingest side is
 * driven by `svpn_tun_ingest`; an internal mpsc queue means there's no file
 * descriptor between Swift and Rust.
 *
 * Returns 0 on success, -1 on error (inspect `svpn_core_last_error`).
 *
 * # Safety
 * `ctx` is opaque to Rust but must remain valid for any dispatch that occurs
 * between this call and `svpn_tun_stop_blocking`. `cb` must be a non-null C
 * function pointer that stays valid for the lifetime of the tunnel.
 * `config_json` must be a NUL-terminated UTF-8 string.
 */
int svpn_tun_start(void *ctx, SvpnWritePacket cb, const char *config_json);

/**
 * Perform the auto-IP assignment handshake and write the server-assigned tunnel
 * IPv4 address (dotted-decimal, NUL-terminated) into `out`/`out_cap`.
 *
 * This is a standalone, blocking one-shot the NE calls **before**
 * `setTunnelNetworkSettings` when the active profile has `auto_ip` enabled: the
 * assigned address becomes the TUN interface address, which iOS fixes before the
 * data plane (`svpn_tun_start`) runs. It binds its own temporary UDP socket and
 * does the encrypted `Control::Request` → `Control::Assign` round-trip (retrying
 * a few times), independent of any running session.
 *
 * `config_json` is the same blob passed to `svpn_tun_start` (only `server`,
 * `password`, `cipher`, and `obfs` are consulted here). Returns 0 on success,
 * -1 on error (inspect `svpn_core_last_error`): a malformed config, a socket
 * failure, a server NAK, or exhausted retries. On success the assigned address
 * is at most 15 chars, so a 16-byte `out` always suffices.
 *
 * # Safety
 * `config_json` must be a NUL-terminated UTF-8 string. `out` must reference
 * `out_cap` writable bytes if non-NULL.
 */
int svpn_request_address(const char *config_json, char *out, int out_cap);

/**
 * Feed a raw IP packet from `NEPacketTunnelFlow.readPackets` into the data
 * plane. Returns 0 if the packet was queued (or dropped under backpressure),
 * -1 if the tunnel isn't running. Non-blocking; callers shouldn't hold
 * `readPackets` completion handlers waiting.
 *
 * # Safety
 * `data` must reference `len` bytes of readable memory.
 */
int svpn_tun_ingest(const uint8_t *data, uintptr_t len);

/**
 * Stop the data plane. Idempotent. Fire-and-forget: the session tasks drain on
 * the runtime after this returns. Use only when the egress `ctx` is retained
 * until a later start or an explicit blocking stop.
 */
void svpn_tun_stop(void);

/**
 * Stop the data plane and BLOCK until the egress task (the only caller of the
 * `SvpnWritePacket` callback) has fully torn down. Once this returns, the
 * egress callback is guaranteed never to fire again, so the caller may safely
 * release the `ctx` it passed to `svpn_tun_start` — required for a terminal
 * stop, where releasing the writer while the egress task is still draining is a
 * use-after-free. Call from a NON-runtime thread (the Swift tunnel control
 * queue). Idempotent.
 */
void svpn_tun_stop_blocking(void);

/**
 * Returns 1 if the data plane is running, 0 otherwise.
 */
int svpn_is_running(void);

/**
 * Write cumulative upload/download byte counters (plaintext IP bytes). Safe to
 * call before `svpn_tun_start` — returns zero counters.
 *
 * # Safety
 * `up` and `down`, if non-NULL, must reference writable 64-bit integer slots.
 */
void svpn_engine_traffic(int64_t *up, int64_t *down);

/**
 * Resident memory size of the FFI's containing process, in bytes — the same
 * number macOS jetsam compares against the 50 MiB PacketTunnel cap, so Swift
 * can chart the on-device RSS curve. Returns 0 on platforms where the mach
 * call isn't available (non-Apple targets).
 */
uint64_t svpn_resident_bytes(void);

#endif  /* SHADOWVPN_CORE_H */
